name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    environment: Labo0

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        working-directory: src
        run: |
          python -m pytest

      - name: Déploiement via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd log430-a25-labo0
            git pull origin main
